name: DiscordNickTag
version: 1.0.0
main: com.github.iamtakagi.discordnicktag.DiscordNickTag
author: iamtakagi
api-version: 1.20
depend: [NametagEdit]
commands:
  discordnicktag:
    description: DiscordNickTag command
    usage: /<command>
    permission: dnt.command
    aliases: [dnt]